name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_COLOR: true
    steps:
    - uses: actions/checkout@v2
    # Based on https://github.com/snyk/snyk/blob/master/.github/workflows/smoke-tests.yml
    
    # Shellspec base image does not have curl, jq, awk, sed
    - name: Build Shellspec image
      working-directory: test
      run: |
        docker build . -t 'farosai/shellspec:kcov'
    
    - name: Run ShellSpec tests
      run: |
        docker run --rm \
          -v "$PWD/test:/src" \
          -v "$PWD/airbyte-local.sh:/airbyte-local.sh" \
          farosai/shellspec:kcov

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
