name: CI

on:
  push:
    branches:
    - main
    - jg/nodecli-release-test
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == 'refs/heads/jg/nodecli-release-test'
    outputs:
      createdTag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Create tag
        id: create-tag
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: cat airbyte-local-cli-nodejs/package.json | jq -r '.version'

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        platform: [x64, arm64]
        exclude:
          - os: windows-latest
            platform: arm64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    needs: [tag]
    # Only run if the tag was created
    if: needs.tag.outputs.createdTag != null
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install
        working-directory: airbyte-local-cli-nodejs
        shell: bash
        run: |
          npm ci --no-audit --no-fund
          npm run version

      - name: Package for Platform
        working-directory: airbyte-local-cli-nodejs
        shell: bash
        run: |
          TARGET="${{ runner.os == 'Windows' && 'win' || runner.os == 'macOS' && 'macos' || 'linux' }}-${{ matrix.platform }}"
          echo "TARGET=$TARGET" >> $GITHUB_ENV
          echo "Building for $TARGET"
          npm run pkg-ci -- --target $TARGET --output ./out/pkg/airbyte-local_${TARGET}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: airbyte-local-cli-nodejs/out/pkg/airbyte-local_${{ env.TARGET }}

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [tag, build]
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: airbyte-local-cli-nodejs/out/pkg

      - name: List Downloaded Binaries
        run: ls -R airbyte-local-cli-nodejs/out/pkg

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            airbyte-local-cli-nodejs/out/pkg/release/airbyte-local_linux-x64
            airbyte-local-cli-nodejs/out/pkg/release/airbyte-local_linux-arm64
            airbyte-local-cli-nodejs/out/pkg/release/airbyte-local_macos-x64
            airbyte-local-cli-nodejs/out/pkg/release/airbyte-local_macos-arm64
            airbyte-local-cli-nodejs/out/pkg/release/airbyte-local_win-x64
          tag_name: ${{ needs.tag.outputs.createdTag }}
