name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_COLOR: true
    steps:
    - uses: actions/checkout@v2
    # Based on https://github.com/snyk/snyk/blob/master/.github/workflows/smoke-tests.yml
    
    # Shellspec base image does not have curl, jq, awk, sed
    - name: Build Shellspec image
      working-directory: test
      run: |
        docker build . -t 'farosai/shellspec:kcov'
    
    - name: Run ShellSpec tests
      run: |
        docker run --rm \
          -v "$PWD/test:/src" \
          -v "$PWD/airbyte-local.sh:/airbyte-local.sh" \
          farosai/shellspec:kcov

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Build job for airbyte-local nodejs
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        working-directory: airbyte-local-cli-nodejs
        run: npm install

      - name: Build
        working-directory: airbyte-local-cli-nodejs
        run: npm run build

      - name: Lint
        working-directory: airbyte-local-cli-nodejs
        run: npm run lint

      - name: Test
        working-directory: airbyte-local-cli-nodejs
        run: npm run test

      - name: Package
        working-directory: airbyte-local-cli-nodejs
        run: npm run pkg

      - name: Install ShellSpec
        working-directory: airbyte-local-cli-nodejs
        run: curl -fsSL https://git.io/shellspec | sh

      - name: Execuatble test
        working-directory: airbyte-local-cli-nodejs
        run: ./shellspec --chdir ./test/exec
